name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
            path: node_modules
            key: node_modules-cache
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install Deps
        run: cd backend && npm i
      - name: Build
        run: cd backend && npm run build
      - name: Generate Artifact
        run: cd backend/build && zip -r artifact.zip ./ -X '*.git*'
      - name: Store Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/build/artifact.zip
  lint:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Cache Node Modules
          id: cache-node-modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: node_modules-cache
        - name: Install Dependencies
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: cd backend && npm i
        - name: Lint the code
          run: cd backend && npm run lint
  test:
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Cache Node Modules
          id: cache-node-modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: node_modules-cache
        - name: Install Dependencies
          if: steps.cache-node-modules.outputs.cache-hit != 'true'
          run: cd backend && npm i
        - name: Run Unit Tests
          run: cd backend && npm t